Algoritmo "Exercicio 2"

Var
  numero1, numero2, numero3, numero4, soma1, soma2 : inteiro
inicio

//Entrada

escreva("Entre com o primeiro número: ")
leia(numero1)

escreva("Entre com o segundo número: ")
leia(numero2)

escreva("Entre com o terceiro número: ")
leia(numero3)

escreva("Entre com o quarto número: ")
leia(numero4)

//Processamento

soma1 := numero1 * numero3
soma2 := numero2 + numero4

//Saida

escreval("A multiplicação é: ", soma1)
escreva("A adição é :", soma2)

Fimalgoritmo