Algoritmo "Exercicio 1"

Var
  numero1, numero2, numero3, soma, resultado : inteiro

inicio

//Entrada

escreval("Entre com o primeiro número: ")
leia(numero1)

escreval("Entre com o segundo número: ")
leia(numero2)

escreval("Entre com o terceiro número: ")
leia(numero3)

//Processamento

soma := numero1 + numero2 + numero3

resultado :=soma * soma

//Saida

escreva("Seu resultado é: ", resultado)

Fimalgoritmo